version: '3.8'

services:
  java-app:
    build:
      context: .
      args:
        JAR_FILE: target/*.jar
        USERNAME: myuser
    container_name: my-java-app
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
